# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build_and_run_unit_tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./csharp
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Add zip files required for running tests
        run: |
          (cd resources/geocoding; zip -r ../../resources/geocoding.zip *)
          (cd resources/test/geocoding; zip -r ../../../resources/test/testgeocoding.zip *)
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
