# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "create-new-release-on-new-metadata-update"

on:
  schedule:
    - cron: '0 8 * * 6'
  workflow_dispatch:
#    todo remove
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get new metadata information and create new GitHub release
        timeout-minutes: 30
        run: |
          bash lib/github-actions-metadata-update.sh ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
